// <auto-generated />
using System;
using Csx.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Csx.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CsxDbContext))]
    [Migration("20260813221517_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Csx.Infrastructure.Data.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId", "AssetType", "AssetId")
                        .IsUnique();

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Balance", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(28,10)");

                    b.HasKey("AccountId");

                    b.ToTable("balances");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Candle", b =>
                {
                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Timeframe")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Bucket")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("VolumeCash")
                        .HasColumnType("numeric(28,10)");

                    b.HasKey("FranchiseId", "Timeframe", "Bucket");

                    b.ToTable("candles");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.EloSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Elo")
                        .HasColumnType("numeric(10,2)");

                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MatchId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId", "At");

                    b.ToTable("elo_snapshots");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Entry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("RefId")
                        .HasColumnType("bigint");

                    b.Property<string>("RefType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("entries");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Franchise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Division")
                        .HasColumnType("text");

                    b.Property<decimal>("Elo")
                        .HasColumnType("numeric(10,2)");

                    b.Property<long>("ExternalTeamId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrgId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTeamId")
                        .IsUnique();

                    b.HasIndex("OrgId");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("franchises");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Holding", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CostBasis")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Shares")
                        .HasColumnType("numeric(28,10)");

                    b.HasKey("UserId", "FranchiseId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("holdings", t =>
                        {
                            t.HasCheckConstraint("holdings_shares_nonneg", "\"Shares\" >= 0");
                        });
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.IdempotencyKey", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Key");

                    b.ToTable("idempotency_keys");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.LeagueMatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FranchiseA")
                        .HasColumnType("bigint");

                    b.Property<long>("FranchiseB")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBo3")
                        .HasColumnType("boolean");

                    b.Property<string>("Map")
                        .HasColumnType("text");

                    b.Property<int?>("RoundsA")
                        .HasColumnType("integer");

                    b.Property<int?>("RoundsB")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("FranchiseA");

                    b.HasIndex("FranchiseB");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.MarketEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId", "Id")
                        .IsDescending(false, true);

                    b.ToTable("market_events");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("CashIn")
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxSlippageBps")
                        .HasColumnType("integer");

                    b.Property<string>("QuoteId")
                        .HasColumnType("text");

                    b.Property<string>("RejectCode")
                        .HasColumnType("text");

                    b.Property<decimal?>("SharesIn")
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Org", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("orgs");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Pool", b =>
                {
                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CashReserve")
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("HaltReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsHalted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ResumesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ShareReserve")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("TotalSupply")
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FranchiseId");

                    b.ToTable("pools", t =>
                        {
                            t.HasCheckConstraint("pools_reserves_positive", "\"CashReserve\" > 0 AND \"ShareReserve\" > 0");
                        });
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.PortfolioSnapshot", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<decimal>("Cash")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("HoldingsValue")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric(28,10)");

                    b.HasKey("UserId", "Day");

                    b.ToTable("portfolio_snapshots");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Posting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(28,10)");

                    b.Property<long?>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EntryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("AccountId", "Id")
                        .IsDescending(false, true);

                    b.ToTable("postings");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.PriceTick", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(28,10)");

                    b.Property<long?>("RefId")
                        .HasColumnType("bigint");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId", "At")
                        .IsDescending(false, true);

                    b.ToTable("price_ticks");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.QuoteRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("AvgPrice")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("CashIn")
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FeeCash")
                        .HasColumnType("numeric(28,10)");

                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<long>("PoolSeq")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PriceAfter")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("PriceBefore")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("SharesOut")
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.RosterSeat", b =>
                {
                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscordId")
                        .HasColumnType("text");

                    b.Property<long>("ExternalPlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FranchiseId", "DiscordId");

                    b.HasIndex("DiscordId");

                    b.ToTable("roster_seats");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Settlement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActualMargin")
                        .HasColumnType("integer");

                    b.Property<long?>("CorrectsId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("EloBefore")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ExpectedMargin")
                        .HasColumnType("numeric(10,4)");

                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCorrection")
                        .HasColumnType("boolean");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OppEloBefore")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PriceAfter")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("PriceBefore")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("ShockApplied")
                        .HasColumnType("numeric(10,6)");

                    b.Property<bool>("ShockClamped")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ShockRaw")
                        .HasColumnType("numeric(10,6)");

                    b.Property<decimal>("Surprise")
                        .HasColumnType("numeric(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("MatchId", "FranchiseId", "IsCorrection")
                        .IsUnique();

                    b.ToTable("settlements");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cash")
                        .HasColumnType("numeric(28,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric(28,10)");

                    b.Property<long>("FranchiseId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PriceAfter")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("PriceBefore")
                        .HasColumnType("numeric(28,10)");

                    b.Property<decimal>("Shares")
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("trades");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<bool>("CanTrade")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Balance", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Account", "Account")
                        .WithOne("Balance")
                        .HasForeignKey("Csx.Infrastructure.Data.Balance", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Candle", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Franchise", null)
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.EloSnapshot", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Franchise", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Org", "Org")
                        .WithMany("Franchises")
                        .HasForeignKey("OrgId");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Holding", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csx.Infrastructure.Data.User", "User")
                        .WithMany("Holdings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.IdempotencyKey", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.LeagueMatch", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Franchise", "TeamA")
                        .WithMany()
                        .HasForeignKey("FranchiseA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Csx.Infrastructure.Data.Franchise", "TeamB")
                        .WithMany()
                        .HasForeignKey("FranchiseB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.MarketEvent", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Order", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csx.Infrastructure.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Pool", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Franchise", "Franchise")
                        .WithOne("Pool")
                        .HasForeignKey("Csx.Infrastructure.Data.Pool", "FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.PortfolioSnapshot", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Posting", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csx.Infrastructure.Data.Entry", "Entry")
                        .WithMany("Postings")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.PriceTick", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.RefreshToken", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.RosterSeat", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Franchise", "Franchise")
                        .WithMany("Roster")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Settlement", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csx.Infrastructure.Data.LeagueMatch", "Match")
                        .WithMany("Settlements")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Trade", b =>
                {
                    b.HasOne("Csx.Infrastructure.Data.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csx.Infrastructure.Data.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csx.Infrastructure.Data.Order", "Order")
                        .WithOne("Trade")
                        .HasForeignKey("Csx.Infrastructure.Data.Trade", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Franchise");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Account", b =>
                {
                    b.Navigation("Balance");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Entry", b =>
                {
                    b.Navigation("Postings");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Franchise", b =>
                {
                    b.Navigation("Pool");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.LeagueMatch", b =>
                {
                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Order", b =>
                {
                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.Org", b =>
                {
                    b.Navigation("Franchises");
                });

            modelBuilder.Entity("Csx.Infrastructure.Data.User", b =>
                {
                    b.Navigation("Holdings");
                });
#pragma warning restore 612, 618
        }
    }
}
